import Head from 'next/head';
import Brand from '../components/Brand';
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Semina || Signup</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <section className='bg-navy'>
        <Navbar />
      </section>

      <section className='login header bg-navy'>
        <div className='container'>
          <div className='row row-cols-md-12 row-cols-1 d-flex justify-content-center align-items-center hero'>
            <div className='col-md-6'>
              <div className='hero-headline text-start'>
                Expand Your <br className='d-none d-md-block' />
                Knowledge & Skills
              </div>
              <p className='hero-paragraph text-start'>
                Kami menyediakan berbagai acara terbaik untuk membantu{' '}
                <br className='d-none d-lg-block' />
                anda dalam meningkatkan skills di bidang teknologi
              </p>
            </div>
            <div className='col-md-6'>
              <form
                action=''
                className='form-login d-flex flex-column mt-4 mt-md-0'
              >
                <div className='d-flex flex-column align-items-start'>
                  <label htmlFor='first_name' className='form-label'>
                    First Name
                  </label>
                  <input
                    type='text'
                    placeholder='First name here'
                    className='form-control'
                    id='first_name'
                  />
                </div>

                <div className='d-flex flex-column align-items-start'>
                  <label htmlFor='last_name' className='form-label'>
                    Last Name
                  </label>
                  <input
                    type='text'
                    placeholder='Last name here'
                    className='form-control'
                    id='last_name'
                  />
                </div>

                <div className='d-flex flex-column align-items-start'>
                  <label htmlFor='email_address' className='form-label'>
                    Email
                  </label>
                  <input
                    type='email'
                    className='form-control'
                    id='email_address'
                    placeholder='semina@bwa.com'
                  />
                </div>

                <div className='d-flex flex-column align-items-start'>
                  <label htmlFor='password' className='form-label'>
                    Password (6 characters)
                  </label>
                  <input
                    type='password'
                    className='form-control'
                    id='password'
                    placeholder='Type your password'
                  />
                </div>

                <div className='d-flex flex-column align-items-start'>
                  <label htmlFor='role' className='form-label'>
                    Role
                  </label>
                  <input
                    type='text'
                    className='form-control'
                    id='role'
                    placeholder='ex: Product Designer'
                  />
                </div>
                <div className='d-grid mt-2'>
                  <button className='btn-green'>Sign Up</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </section>

      <Brand className='pt-0 bg-navy' />
    </>
  );
}
